### ISSUE TITLE
Collect ban data

### ISSUE THREAD

**Issue by Shirleh** [Shirleh/Laplace#4]
The goal is to create a new event listener. The event listener listens to ban events, extracts the relevant data points, and write them into InfluxDB.

Starting point: `datacollection.Listeners.kt`

Event class: `BanEvent`

Data points:
- time of the event
- id of the guild member who issued the ban

**Comment by veksen** [comment]
`DateEvent` does not seem to expose a timestamp. Is it okay to use `OffsetDateTime.now()`? Any alternatives?

(I'm giving a stab at this)

**Comment by Shirleh** [comment]
You can use `Instant.now()`! `Point#time` also conveniently accepts `Instant`s, so you can do
```
Point.time(Instant.now(), WritePrecision.S)
```
Without getting _too_ much into the Java Time API, `Instant` is just a little wrapper class around _seconds since epoch_. Other classes such as `OffsetDateTime` contains more to enable you to work with time zones. 

For our use case, we'll assume all time is recorded as _time since epoch_ so we don't have to deal with yucky time zones in the data layer. :smile: 

(Assuming you meant `BanEvent` when you said `DateEvent`, otherwise I'm a little bit confused haha :see_no_evil: )
