### ISSUE TITLE
Collect voice data

### ISSUE THREAD

**Issue by Shirleh** [Shirleh/Laplace#5]
### Goal
Listen on `VoiceStateUpdateEvent`, extract the relevant information from the event into a `Point`, and save it in InfluxDB.

### Requirements
The data `Point` should include the following:
- tag: `guildMemberId`
- tag: `guildId`
- tag: `channelId`
- field `boolean`: `isInVoice`
- field `boolean`: `isMuted`
- field `boolean`: `isDeafened`
- time: current time

**Comment by tomasff** [comment]
What should the channel id be if the user left the channel? the channel id where they were?

**Comment by Shirleh** [comment]
Haaii Tomas! Sorry for poofing lately :see_no_evil: 

The `channelId` should be an empty string so we will be able to distinguish the start and end of a voice session! :smile:

**Comment by tomasff** [comment]
No problem 👌
I have just pushed a new commit to solve the issue with the optionals.
